### ISSUE TITLE
flip arguments for curry support

### ISSUE THREAD

**Issue by timoxley** [jacomyal/typology#18]
Currently can't curry check because of the argument order:
```js
myTypology.check({name: 'alice'}, 'User');
```

If the arguments were flipped we could use a variety of currying tools including built-in `Function.prototype.bind`:
```js
var checkUser = myTypology.check.bind(myTypology, 'User');
checkUser({name: 'alice'})
checkUser({name: 'bob'})
```

Also means the type you're validating against isn't obscured by long variable names or object literals. I think type-first improves readability:

```js
myTypology.check({
  "some": "data",
  "but": "you",
  "won't": "know",
  "what": {
    "type": {
    "we": "are",
    "validating": "until",
    "you": "get",
    "through": "reading",
    "this": {
      "object": "literal"
    }
  }
}, 'TypeNameIsAllTheWayDownHere')
myTypology.check(thisCouldBeAUserButMaybeNot, 'User');
myTypology.check(whatTypeIsThis, 'AnotherUser');
```
vs
```js
myTypology.check('TypeNameIsRightUpFront', {
  "some": "data",
  "but": "you",
  "already": "know",
  "what": {
    "type": {
    "we": "are",
    "validating": "so",
    "you": "don't",
    "need": "to",
    "read": {
      "through": "this"
    }
  }
})
myTypology.check('User', thisCouldBeAUserButMaybeNot);
myTypology.check('AnotherUser', whatTypeIsThis);
```

For the above reasons it's generally a good idea to put the arguments which are least likely to be dynamic first. IMO. Your call.

**Comment by timoxley** [comment]
Flipping arguments for `check` would also make `check` consistent with `add`, whose first argument is the type/name:

```js
myTypology.add('User', {
  firstname: 'string',
  lastname: 'string',
  age: '?number'
});
```

**Comment by Yomguithereal** [comment]
Hello @timoxley. You are entirely right. We are considering swapping the arguments in a further release. We need to rewrite most of the code anyway.

**Comment by jacomyal** [comment]
The v1.0.0 is soon to be published, and the arguments of #check have been flipped.

**Comment by timoxley** [comment]
:D
