### ISSUE TITLE
Custom types are not reusable in array 

### ISSUE THREAD

**Issue by legaultpierre** [jacomyal/typology#23]
Let's say we have defined a custom type `ref`:
``
types.add('ref', {
  key1: 'string'
});``  
We can easily use this custom type in another custom type in the following cases (not exhaustive):
``types.add('custom2', {
  key2: 'ref'
});``
``types.add('custom3', {
  key2: '?ref'
});``
``types.add('custom4', {
  key2: '!ref'
});``
``types.add('custom5', {
  key2: 'ref|string'
});``
But the following (and all its related) do not work:
``types.add('custom6', {
  key2: '[ref]'
});``

**Comment by legaultpierre** [comment]
Went to fast in reading the doc :)

**Comment by Yomguithereal** [comment]
Ach. Didn't have time to tell you so. I suppose you went with:

```js
types.add('custom6', { key2: ['ref'] });
```

**Comment by legaultpierre** [comment]
Ahah exactly.

**Comment by Yomguithereal** [comment]
Shawarma then.
